import { useMemo, useState } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { apiRequest, queryClient } from "../lib/queryClient";
import { Button } from "../components/ui/button";
import { Card } from "../components/ui/card";
import { Skeleton } from "../components/ui/skeleton";
import { Badge } from "../components/ui/badge";
import { useToast } from "../hooks/use-toast";
import { useIsMobile } from "../hooks/use-mobile";
import { toFantasyCardData } from "../lib/fantasy-card-adapter";
import CollectionStableCard from "../components/cards/CollectionStableCard";
import { type PlayerCardWithPlayer, type Lineup } from "../../../shared/schema";
import { Archive, Crown, DollarSign, Gem, ShieldCheck, Sparkles } from "lucide-react";

type RarityKey = "all" | "common" | "rare" | "epic" | "unique" | "legendary";
const BASE_PRICES: Record<string, number> = { common: 0, rare: 20, unique: 50, epic: 50, legendary: 100 };
function rarityOf(card: PlayerCardWithPlayer) { return String(card.rarity || "common").toLowerCase(); }
function money(value: unknown) { const n = Number(value || 0); return Number.isFinite(n) ? `N$${n.toFixed(2)}` : "N$0.00"; }
function normalizeCards(data: unknown): PlayerCardWithPlayer[] { if (Array.isArray(data)) return data as PlayerCardWithPlayer[]; if (Array.isArray((data as any)?.cards)) return (data as any).cards; return []; }

export default function CollectionCleanPage() {
  const { toast } = useToast();
  const isMobile = useIsMobile();
  const [filter, setFilter] = useState<RarityKey>("all");
  const [editingLineup, setEditingLineup] = useState(false);
  const [selectedForLineup, setSelectedForLineup] = useState<Set<number>>(new Set());
  const { data: cards = [], isLoading } = useQuery<PlayerCardWithPlayer[]>({ queryKey: ["/api/user/cards"], queryFn: async () => { const res = await fetch("/api/user/cards", { credentials: "include" }); if (!res.ok) throw new Error("Failed to fetch cards"); return normalizeCards(await res.json()); } });
  const { data: lineupData } = useQuery<{ lineup: Lineup; cards: PlayerCardWithPlayer[] }>({ queryKey: ["/api/lineup"], queryFn: async () => { const res = await fetch("/api/lineup", { credentials: "include" }); if (!res.ok) throw new Error("Failed to fetch lineup"); return res.json(); } });
  const saveLineupMutation = useMutation({ mutationFn: async (cardIds: number[]) => (await apiRequest("POST", "/api/lineup", { cardIds })).json(), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["/api/user/cards"] }); queryClient.invalidateQueries({ queryKey: ["/api/lineup"] }); setEditingLineup(false); toast({ title: "Lineup saved" }); }, onError: (error: any) => toast({ title: "Error", description: error.message, variant: "destructive" }) });
  const listMutation = useMutation({ mutationFn: async ({ cardId, price }: { cardId: number; price: number }) => (await apiRequest("POST", "/api/marketplace/list", { cardId, price })).json(), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["/api/user/cards"] }); queryClient.invalidateQueries({ queryKey: ["/api/marketplace"] }); toast({ title: "Card listed" }); }, onError: (error: any) => toast({ title: "Error", description: error.message || "Failed to list card", variant: "destructive" }) });
  const cancelMutation = useMutation({ mutationFn: async (cardId: number) => (await apiRequest("POST", `/api/marketplace/cancel/${cardId}`, {})).json(), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["/api/user/cards"] }); queryClient.invalidateQueries({ queryKey: ["/api/marketplace"] }); toast({ title: "Listing cancelled" }); }, onError: (error: any) => toast({ title: "Error", description: error.message || "Failed to cancel", variant: "destructive" }) });
  const counts = useMemo(() => { const base: Record<string, number> = { common: 0, rare: 0, epic: 0, unique: 0, legendary: 0 }; cards.forEach((card) => { const r = rarityOf(card); if (base[r] !== undefined) base[r] += 1; }); return base; }, [cards]);
  const filteredCards = useMemo(() => cards.filter((card) => filter === "all" || rarityOf(card) === filter), [cards, filter]);
  function startEditLineup() { setEditingLineup(true); setSelectedForLineup(new Set(lineupData?.lineup?.cardIds || [])); }
  function toggleLineupCard(cardId: number) { setSelectedForLineup((prev) => { const next = new Set(prev); if (next.has(cardId)) next.delete(cardId); else if (next.size < 5) next.add(cardId); return next; }); }
  function sellCard(card: PlayerCardWithPlayer) { const rarity = rarityOf(card); if (rarity === "common") return toast({ title: "Cannot sell common cards", variant: "destructive" }); listMutation.mutate({ cardId: card.id, price: BASE_PRICES[rarity] || 1 }); }
  const filters = [ { value: "all" as RarityKey, label: "All", icon: <Archive className="h-4 w-4" />, count: cards.length }, { value: "common" as RarityKey, label: "Common", icon: <ShieldCheck className="h-4 w-4" />, count: counts.common }, { value: "rare" as RarityKey, label: "Rare", icon: <Sparkles className="h-4 w-4" />, count: counts.rare }, { value: "epic" as RarityKey, label: "Epic", icon: <Sparkles className="h-4 w-4" />, count: counts.epic }, { value: "unique" as RarityKey, label: "Unique", icon: <Gem className="h-4 w-4" />, count: counts.unique }, { value: "legendary" as RarityKey, label: "Legendary", icon: <Crown className="h-4 w-4" />, count: counts.legendary } ];
  return <main className="min-h-screen bg-[#070b18] px-3 pb-32 pt-4 text-white sm:px-6"><div className="mx-auto max-w-7xl space-y-5"><Card className="border-white/10 bg-white/[0.06] p-4 text-white backdrop-blur-xl"><p className="text-xs font-black uppercase tracking-[0.22em] text-violet-300/80">Collection</p><h1 className="text-2xl font-black">My Cards</h1><p className="text-sm text-white/50">{cards.length} cards owned • {cards.filter((card) => card.forSale).length} listed</p><div className="mt-4 flex gap-2 overflow-x-auto pb-1">{filters.map((item) => <Button key={item.value} variant={filter === item.value ? "default" : "outline"} size="sm" onClick={() => setFilter(item.value)} className="shrink-0 gap-1">{item.icon}{item.label}<span className="ml-1 text-xs opacity-70">{item.count || 0}</span></Button>)}</div><div className="mt-3 flex gap-2"><Button variant="outline" size="sm" onClick={startEditLineup}>Edit Lineup</Button>{editingLineup ? <Button size="sm" onClick={() => saveLineupMutation.mutate(Array.from(selectedForLineup))} disabled={saveLineupMutation.isPending || selectedForLineup.size !== 5}>Save ({selectedForLineup.size}/5)</Button> : null}</div></Card>{isLoading ? <div className="grid grid-cols-2 justify-items-center gap-x-3 gap-y-6 sm:grid-cols-3 lg:grid-cols-5 xl:grid-cols-6">{Array.from({ length: 10 }).map((_, index) => <Skeleton key={index} className="h-[226px] w-[160px] rounded-[18px] bg-slate-800" />)}</div> : filteredCards.length ? <div className="grid grid-cols-2 justify-items-center gap-x-3 gap-y-6 sm:grid-cols-3 lg:grid-cols-5 xl:grid-cols-6">{filteredCards.map((card) => { const fantasyCard = toFantasyCardData(card, { imageWidth: 640 }); const rarity = rarityOf(card); const isSelected = selectedForLineup.has(card.id); return <div key={card.id} className="flex w-full max-w-[180px] flex-col items-center gap-2"><div className="relative">{card.forSale ? <Badge className="absolute left-2 top-2 z-20 bg-amber-400 text-black">Listed</Badge> : null}<CollectionStableCard player={fantasyCard} selected={isSelected} onClick={editingLineup ? () => toggleLineupCard(card.id) : undefined} showPrice={Boolean(card.forSale)} size={isMobile ? "sm" : "md"} /></div>{card.forSale ? <Button size="sm" variant="destructive" onClick={() => cancelMutation.mutate(card.id)} disabled={cancelMutation.isPending} className="h-8 w-full text-[11px] font-black">Cancel {money(card.price)}</Button> : rarity === "common" ? <Button size="sm" variant="outline" disabled className="h-8 w-full text-[11px] font-black">Tournament Only</Button> : <Button size="sm" onClick={() => sellCard(card)} disabled={listMutation.isPending} className="h-8 w-full bg-gradient-to-r from-emerald-400 to-lime-300 text-[11px] font-black text-black"><DollarSign className="mr-1 h-3 w-3" /> Sell</Button>}</div>; })}</div> : <Card className="border-white/10 bg-white/[0.06] p-8 text-center text-white"><p className="text-white/60">No cards found with this filter.</p></Card>}</div></main>;
}
